bigeneral: astargeneral.cpp astargeneral
	g++ astargeneral.cpp -o astargeneral
bi: astarbidirectional.cpp astarbidirectional
	g++ astarbidirectional.cpp -o astarbidirectional
monotone: astarmonotone.cpp astarmonotone 
	g++ astarmonotone.cpp -o astarmonotone
clean:
	rm -f astarmonotone astarbidirectional astargeneral
